/* eslint-disable */
// notarial demo - top-level App.
// All state mutations go through the backend; the frontend renders what it gets.

const { useState, useEffect, useMemo, useRef, Fragment } = React;

const ControlBar = window.ControlBar;
const LeftRail = window.LeftRail;
const Center = window.Center;
const RightRail = window.RightRail;
const ErrorBoundary = window.ErrorBoundary;

// ---------- helpers ----------
const sevLabel = (s) => ({2:"crit",3:"err",4:"warn",5:"notice",6:"info"}[s] || "info");
const sevClass = (s) => `sev-${s}`;
const ORG_OF_SRC = { nsl:"notary", wwftrace:"notary", cdr:"knb", vis:"knb", ech:"external", syvas:"external",
  registernotariaat:"knb", brn:"knb", ogn:"knb", pec:"knb" };
const ORG_LABEL = { notary:"NOTARY", knb:"KNB", external:"EXTERNAL" };

// ---------- precomputed state ----------
// Every (scenario, cursor) payload is generated by build_states.py and shipped
// as window.PRECOMPUTED; navigation is a local cursor change, no backend calls.
const PRECOMPUTED = window.PRECOMPUTED || { default: "deed", governance: {}, states: {} };

// Governance is identical across all states, so mirror it into window.* once.
window.LOG_SOURCES = PRECOMPUTED.governance.log_sources || [];
window.SPECS = PRECOMPUTED.governance.specs || [];
window.SCHEMAS = PRECOMPUTED.governance.schemas || [];

// Rebuild the payload for a (scenario, cursor), re-attaching shared governance.
function buildPayload(scenario, cursor) {
  const entries = PRECOMPUTED.states[scenario] || [];
  const idx = Math.max(0, Math.min(cursor, entries.length - 1));
  return { ...entries[idx], governance: PRECOMPUTED.governance };
}

// =====================================================================
//   ROOT
// =====================================================================
function App() {
  // Active example + step are the only "state" now, held locally in the browser.
  const [scenario, setScenario] = useState(PRECOMPUTED.default || "deed");
  const [cursor, setCursor] = useState(0);
  const payload = useMemo(() => buildPayload(scenario, cursor), [scenario, cursor]);

  const [view, setView] = useState("layer");
  const [highlight, setHighlight] = useState(null);
  const [selectedEntry, setSelectedEntry] = useState(null);
  // UI layout toggles - sidebars collapsed by default
  const [leftOpen, setLeftOpen] = useState(false);
  const [rightOpen, setRightOpen] = useState(false);
  const [expandedText, setExpandedText] = useState(false);
  const [expandMiddle, setExpandMiddle] = useState(false);
  // Process-content language for the EN/NL switcher. Defaults to EN on load and
  // only affects process content (step titles, narration, actor names), never the
  // UI chrome. Toggling is React state, so the whole tree re-renders - no reload.
  const [lang, setLang] = useState("en");

  const prevCount = useRef(0);
  useEffect(() => {
    if (!payload) return;
    const regs = payload.state.reg;
    const n = regs.length;
    if (n > prevCount.current) {
      const news = regs.slice(prevCount.current).map((r) => r.id);
      setHighlight({ kind: "reg", ids: news, at: Date.now() });
      const t = setTimeout(() => setHighlight(null), 1400);
      prevCount.current = n;
      return () => clearTimeout(t);
    }
    prevCount.current = n;
  }, [payload?.state?.reg?.length]);

  const total = (PRECOMPUTED.states[scenario] || []).length;

  const next = () => setCursor((c) => Math.min(c + 1, total - 1));
  const prev = () => setCursor((c) => Math.max(c - 1, 0));
  const reset = () => { prevCount.current = 0; setCursor(0); };
  const onScenario = (s) => { prevCount.current = 0; setScenario(s); setCursor(0); };

  const { state, step } = payload;

  return (
    <div className="app">
      <ControlBar
        step={step}
        cursor={cursor}
        total={total}
        scenario={scenario}
        onPrev={prev}
        onNext={next}
        onReset={reset}
        onScenario={onScenario}
        leftOpen={leftOpen}
        rightOpen={rightOpen}
        onToggleLeft={() => setLeftOpen(o => !o)}
        onToggleRight={() => setRightOpen(o => !o)}
        expandedText={expandedText}
        onToggleText={() => setExpandedText(t => !t)}
        expandMiddle={expandMiddle}
        onToggleExpandMiddle={() => setExpandMiddle(m => !m)}
        lang={lang}
        onToggleLang={() => setLang(l => l === "en" ? "nl" : "en")}
      />
      <ErrorBoundary resetKey={`${scenario}|${cursor}|${view}|${selectedEntry}`}>
        <div className={`grid ${leftOpen ? "" : "no-left"} ${rightOpen ? "" : "no-right"} ${expandMiddle ? "expand-mid" : ""}`}>
          {leftOpen && <LeftRail step={step} cursor={cursor} scenario={scenario} expandedText={expandedText} lang={lang} />}
          <Center
            state={state}
            step={step}
            view={view}
            setView={setView}
            highlight={highlight}
            selectedEntry={selectedEntry}
            setSelectedEntry={setSelectedEntry}
            cursor={cursor}
            expandedText={expandedText}
            lang={lang}
          />
          {rightOpen && <RightRail state={state} step={step} scenario={scenario} selectedEntry={selectedEntry} expandedText={expandedText} lang={lang} />}
        </div>
      </ErrorBoundary>
      <footer className="app-footer">
        This demonstration was developed with the assistance of AI tools. The processes shown are exemplary processes drawn from the notarial domain, not exhaustive or authoritative descriptions of actual notarial workflows. Source code and a link to the thesis are available on <a href="https://github.com/eisedevries/notarial-audit-log-demo" target="_blank" rel="noopener" style={{color:"var(--knb-dark)",textDecoration:"none"}}>GitHub</a>.
      </footer>
    </div>
  );
}

window.App = App;
